### ISSUE TITLE
Request: Document how this project related to the Redpoint clang-tidy for Unreal product

### ISSUE THREAD

**Issue by rlabrecque** [RedpointGames/llvm-project#5]
I got to this repo by looking for clang-tidy for Unreal again; and this is obviously the like the current state of that; but for anyone that knew about it originally; is it just fully open source now with no more paid product? What does this mean for this project long term? Do you still have any paid support for this?

I'm sure people that had purchased seats to use clang-tidy got some good info but seeing this was quite a [pleasant] surprise!

**Comment by hach-que** [comment]
Correct! This replaces the "clang-tidy for Unreal Engine" project completely. There's no more paid subscription licensing; you're free to use this regardless of organisation size under the existing LLVM/Clang open source license. I'll add the info below to the Wiki of this project for other people as well.

### Comparison with clang-tidy for Unreal Engine

The "clang-tidy for Unreal Engine" project worked by adding additional commands to the action graph, which meant that you'd parse your C++ code twice - once under MSVC, and a second time for clang-tidy to run. The compilation time impact of this meant our larger paying customers of "clang-tidy for Unreal Engine" generally ended up licensing it to only run on build servers, as it was too slow to run on developer machines.

Not only does this mean that we weren't licensing it at at a scale to dedicate resources to supporting/maintaining it, but it was also far less ideal as a development experience for our customers - for a developer working on C++ code, finding out that you have a regression on an overnight build is a much poorer development experience that finding out immediately as you're developing on your local machine.

The only solution to this problem was to integrate the static analysis directly into the Clang compiler itself, which is what this fork does. Rather than a separate action graph step, it runs the static analysis in between Clang parsing the C++ code and performing LLVM codegen. It also runs the static analysis rules in parallel, and only for the files you want, which makes it much much faster than clang-tidy in general ([Performance](https://github.com/RedpointGames/llvm-project/wiki/Performance) goes into more detail on this).

### Paid support for this project

Since this now falls under our open source projects, there's no off-the-shelve paid subscription for support. For most people using it, it is made available on an "as-is" basis. Development of this project is driven by what needs I have internally for working on the paid plugins I offer on the Marketplace.

However, if you have specific support requirements in mind and are looking for commercial support, we can probably draft up a bespoke support agreement. Given it'd be a one-off at this stage, pricing would probably be similar to our [Premium support plan](https://licensing.redpoint.games/support/plans). If you're interested, reach out to sales@redpoint.games and we can discuss further.

**Comment by rlabrecque** [comment]
That's exactly the type of thing I was looking for [on the wiki initially]. Thanks!

Closing this out with that info living here now: https://github.com/RedpointGames/llvm-project/wiki/Comparison-with-%22clang%E2%80%90tidy-for-Unreal-Engine%22
